import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    marginBottom: 30,
  },
  headerContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 100,
  },
  emptyText: {
    marginTop: 10,
    fontSize: 16,
    color: '#999',
    textAlign: "center",
    fontWeight: "500",
  },
  headerTextFlatList: {
    marginBottom: 12,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 16,
  },
  cardsContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  cardContent: {
    backgroundColor: '#1CBDCF',
    marginBottom: 14,
    borderRadius: 10,
    width: 320,
    height: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textContent: {
    color: '#fff',
    paddingLeft: 12,
    paddingRight: 12,
  },
  textPressableContent: {
    color: '#1CBDCF',
  },
  concluirPressable: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: '#fff',
    width: 100,
    height: 30,
    borderRadius: 10,
    margin: 6,
    marginLeft: 8,
    shadowRadius: 2,
  },
  button: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 60,
  },
  pdfContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 15,
    padding: 20,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: '#333',
    marginBottom: 15,
    textAlign: "center",
  },
  inputObservacao: {
    width: "100%",
    height: 100,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    backgroundColor: '#f9f9f9',
    textAlignVertical: "top",
    fontSize: 16,
    marginBottom: 20,
  },
  modalPressables: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pressCancelar: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8,
    marginRight: 10,
    alignItems: "center",
  },
  pressConfirmar: {
    flex: 1,
    backgroundColor: '#1CBDCF',
    padding: 12,
    borderRadius: 8,
    marginLeft: 10,
    alignItems: "center",
  },
  pressTextCancelar: {
    color: '#666',
    fontWeight: "bold",
  },
  pressTextConfirmar: {
    color: "white",
    fontWeight: "bold",
  },
  logoHeader: {
    fontSize: 20,
    fontWeight: "bold",
    color: '#1CBDCF',
    fontFamily: "Inria Sans",
  },
});
